Multi Spin Bot
evgfilim1/py_mbot pull request #2
Opened 2017-06-05 12:31 UTC by mrsteyk

Title speaks for itself!

2017-06-05 12:31 UTC, mrsteyk commented
Github is strange shit

2017-06-05 12:34 UTC, OlexiyUA commented
@mrsteyk +

2017-06-05 12:44 UTC, evgfilim1 requested changes

2017-06-05 12:44 UTC, evgfilim1 commented on modules/multi_spin.py
> +    def _is_private(self, chat_id):
This can be static method, I think

2017-06-05 12:44 UTC, evgfilim1 commented on modules/multi_spin.py
> +        #pass
Please, remove useless and debugging comments in code (not only here)

2017-06-05 12:44 UTC, evgfilim1 commented on modules/multi_spin.py
> +                self.chat_users[chat_id]={}
Put spaces between `=`

2017-06-05 12:44 UTC, evgfilim1 commented on .gitignore
> +*.swp
For what it is?

2017-06-05 12:44 UTC, evgfilim1 commented on modules/multi_spin.py
> +        self._telegram_api._dispatcher.add_handler(MessageHandler(Filters.all, self.update_cache, edited_updates=True),
Please, don't use lines longer than 100 symbols

2017-06-05 12:45 UTC, evgfilim1 commented
Btw, what's going on with GitHub? It tries to add lines that are already in code

2017-06-05 12:46 UTC, mrsteyk commented
@evgfilim1 Its git and not github

2017-06-05 12:46 UTC, evgfilim1 commented
@mrsteyk Okay, you're right

2017-06-05 17:22 UTC, mrsteyk commented on .gitignore
> +*.swp
VIM

2017-06-06 15:22 UTC, sojalei commented
modules/multi_spin.py line 99 _mardown_

2017-06-06 15:30 UTC, evgfilim1 requested changes

2017-06-06 15:30 UTC, evgfilim1 commented on modules/multi_spin.py
> +                                                     mardown=True)
You've mistyped, this line should be `markdown=True`
____
Thanks, @sojalei

2017-06-06 16:34 UTC, evgfilim1 requested changes

2017-06-06 16:34 UTC, evgfilim1 commented on modules/multi_spin.py
> +         ["_Ищем рандомного кота на улице..._", "_Ищем палку..._", "_Ищем шапку..._", "_Рисуем ASCII-арт..._",
This line is longer than 100 symbols

2017-06-06 16:34 UTC, evgfilim1 commented on modules/multi_spin.py
> +
Here should be _two_ empty lines (between code and class definition)

2017-06-06 16:34 UTC, evgfilim1 commented on modules/multi_spin.py
> +
Here and below shoul be _one_ empty line (between methods in class)

2017-06-06 16:38 UTC, evgfilim1 commented
Module refuses to load and even to work: `[Errno 2] No such file or directory: 'spins.pkl'`
And this: 
```
ERROR:telegram.ext.dispatcher:An uncaught error was raised while processing the update
Traceback (most recent call last):
...
  File "/home/evgen/Work/py_mbot/modules/multi_spin.py", line 109, in update_cache
    self.chat_users[chat_id].update({user.id: user.name})
AttributeError: 'TelegramModule' object has no attribute 'chat_users'`
```

2017-06-06 16:43 UTC, mrsteyk commented
ЩА ВСЁ БУИТ _)))

2017-06-06 16:45 UTC, mrsteyk commented
@evgfilim1 should work

2017-06-06 16:46 UTC, mrsteyk commented on modules/multi_spin.py
> +         ["_Ищем рандомного кота на улице..._", "_Ищем палку..._", "_Ищем шапку..._", "_Рисуем ASCII-арт..._",
Well fuck you then

2017-06-06 16:46 UTC, mrsteyk commented on modules/multi_spin.py
> +
*dropped an F bomb*

2017-06-07 18:25 UTC, evgfilim1 requested changes

2017-06-07 18:25 UTC, evgfilim1 commented on modules/multi_spin.py
> +         "Сегодня ты *{s} дня,* {n}"],
Indent it:
```
SOMETHING = [e1, e2, e3, 
             e4, e5]
```

2017-06-07 18:26 UTC, mrsteyk commented on modules/multi_spin.py
> +         "Сегодня ты *{s} дня,* {n}"],
fuck you

2017-06-07 18:26 UTC, mrsteyk commented on modules/multi_spin.py
> +         "Сегодня ты *{s} дня,* {n}"],
it works

2017-06-07 18:30 UTC, mrsteyk commented
@evgfilim1

2017-06-07 19:05 UTC, evgfilim1 approved these changes

2017-06-07 19:05 UTC, evgfilim1 commented
Merged

2017-06-07 19:05 UTC, closed without merging