added module loading messages
evgfilim1/py_mbot pull request #5
Opened 2017-06-07 11:00 UTC by usernameak

2017-06-07 11:16 UTC, sojalei commented
maybe need use logger

2017-06-07 14:05 UTC, evgfilim1 commented
Couldn't you use `.format()` instead of `'%s'`

2017-06-07 14:05 UTC, OctoNezd commented
@evgfilim1 %s > format

2017-06-07 14:05 UTC, usernameak commented
@OctoNezd +

2017-06-07 14:08 UTC, evgfilim1 commented
Sorry, but you have to use it to follow code standard (I don't like when styles are mixed)

2017-06-07 14:08 UTC, OctoNezd commented
@evgfilim1 then switch to %!

2017-06-07 14:09 UTC, usernameak commented
@evgfilim1 but... the logger supports additional args for %s

2017-06-07 14:39 UTC, evgfilim1 commented
@OctoNezd @usernameak Okay, I'll fix it myself, if you don't want to.

2017-06-07 14:45 UTC, evgfilim1 requested changes
I can do this myself, but you should know about these changes

2017-06-07 14:45 UTC, evgfilim1 commented on modloader.py
> +
This newline is extra

2017-06-07 14:45 UTC, evgfilim1 commented on modloader.py
> +        else: continue
`continue` must be on a new line

2017-06-07 14:45 UTC, evgfilim1 commented on modloader.py
> +
Another extra newline

2017-06-07 15:05 UTC, evgfilim1 commented on modloader.py
> +        else: continue
And module can be a package (directory, which contains `__init__.py` file)

2017-06-07 16:53 UTC, evgfilim1 approved these changes

2017-06-07 16:53 UTC, merged

2017-06-07 17:27 UTC, OctoNezd commented
WHAT HAVE YOU DONE YOU IMBECIL

2017-06-07 18:01 UTC, usernameak commented
@OctoNezd сам имбицил

2017-06-07 18:02 UTC, OctoNezd commented
@usernameak я про ебгена

2017-06-07 18:02 UTC, usernameak commented
@usernameak кааааааааааааааааааааак?

2017-06-08 19:00 UTC, dansenpir commented
@usernameak Tem o código dele em algum Git?

2017-06-08 19:45 UTC, evgfilim1 commented
@dansenpir English, please