add new localization
evgfilim1/py_mbot pull request #7
Opened 2017-06-10 17:37 UTC by sojalei

need testing,
P:S I lose my phone and now i can't open telegram

2017-06-10 17:51 UTC, evgfilim1 requested changes

2017-06-10 17:51 UTC, evgfilim1 commented on lang/irc.json
> +    "help" : "Эквивалент Ирки /me command"
> /me command

English words in Russian strings... Fix it

2017-06-10 17:51 UTC, evgfilim1 commented on lang/kickban.json
> +    "kicked": "{0} кикнутые {1}",
I think there should be "кикнул(-а)" and so on

2017-06-10 17:51 UTC, evgfilim1 commented on lang/ping.json
> +    "help": "Этот модуль отвечает \"Pong!\" на /ping command",
> /ping command

See first comment

Also, "Pong!" here, but "Понг!" below. I think it should be fixed

2017-06-10 17:51 UTC, evgfilim1 commented on lang/whoami.json
> +    "info_forward": "Отослано с {0}\nОтослано с АйДи: {1}"
I think there should be "Переслано с ..."

2017-06-10 17:51 UTC, evgfilim1 commented on lang/msgdel.json
> +    "help": "Этот модуль удаляет сообщения отправленные ботом\nИспользовать:\nОтветить на сообщение которое вы хотите удалить и написать /delete"
Fix it: 
- "сообщения`,` отправленные"
- "сообщение`,` которое ...`,` и написать"

2017-06-11 15:55 UTC, sojalei commented
check

2017-06-11 19:01 UTC, evgfilim1 requested changes
Last thing before merging

2017-06-11 19:01 UTC, evgfilim1 commented on lang/irc.json
> +    "help" : "Эквивалент Ирки /me комманда"
I think this should be "Эквивалент команды /me в Ирке" (also fix translation below)

2017-06-11 19:01 UTC, evgfilim1 commented on lang/ping.json
> +    "help": "Этот модуль отвечает \"Понг!\" на /ping комманда",
"... на команду /ping", I think

2017-06-11 19:01 UTC, evgfilim1 commented on lang/msgdel.json
> +    "help": "Этот модуль удаляет сообщения, отправленные ботом\nИспользовать:\nОтветить на сообщение, которое вы хотите удалить, и написать /delete"
Put "Как использовать:" or "Доступные команды:" instead

2017-06-12 16:50 UTC, evgfilim1 approved these changes

2017-06-12 16:50 UTC, merged